# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Matteo Belenchia
tagline:          'Curriculum Vitae'
description:      ''
url:              https://097475.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
plugins: 
  - jekyll-paginate
  - jekyll-gist
 
paginate:            5
paginate_path:       "page:num"

